export const ASSETS = {
  background: { key: 'moonshadow-ridge', path: '/assets/environment/moonshadow-ridge.webp' },
  extendedRegionBackgrounds: {
    wonju: { key: 'wonju-chiaksan-v3', path: '/assets/environment/generated/wonju-chiaksan-v3.webp' },
    gangneung: { key: 'gangneung-gyeongpo-v3', path: '/assets/environment/generated/gangneung-gyeongpo-v3.webp' },
    haeju: { key: 'haeju-saltfield-v3', path: '/assets/environment/generated/haeju-saltfield-v3.webp' },
    geoje: { key: 'geoje-naval-strait-v3', path: '/assets/environment/generated/geoje-naval-strait-v3.webp' },
  },
  episode2TerrainBases: {
    'northwest-road': { key: 'episode2-northwest-road-base-v1', path: '/assets/environment/episode2/episode2-northwest-road-base-v1.webp' },
    'mountain-road': { key: 'episode2-mountain-road-base-v1', path: '/assets/environment/episode2/episode2-mountain-road-base-v1.webp' },
    'central-river': { key: 'episode2-central-river-base-v1', path: '/assets/environment/episode2/episode2-central-river-base-v1.webp' },
    'west-coast': { key: 'episode2-west-coast-base-v1', path: '/assets/environment/episode2/episode2-west-coast-base-v1.webp' },
    'honam-road': { key: 'episode2-honam-road-base-v1', path: '/assets/environment/episode2/episode2-honam-road-base-v1.webp' },
    'yeongnam-road': { key: 'episode2-yeongnam-road-base-v1', path: '/assets/environment/episode2/episode2-yeongnam-road-base-v1.webp' },
  },
  episode2WaterBank: {
    key: 'episode2-water-bank-v1',
    path: '/assets/environment/episode2/episode2-water-bank-v1.webp',
  },
  ulleungdoPrisonBackground: { key: 'ulleungdo-prison-gates-aligned-v2', path: '/assets/environment/ulleungdo-prison-gates-aligned-v2.webp' },
  ulleungCoastalForestBackground: { key: 'ulleung-coastal-forest-v1', path: '/assets/environment/ulleung-coastal-forest-v1.webp' },
  ulleungSilvergrassMeadowBackground: { key: 'ulleung-silvergrass-meadow-v1', path: '/assets/environment/ulleung-silvergrass-meadow-v1.webp' },
  ulleungdoTrainingGroundBackground: { key: 'ulleung-raided-village-v2', path: '/assets/environment/ulleung-raided-village-v2.webp' },
  ulleungHighlandRidgeBackground: { key: 'ulleung-highland-ridge-v1', path: '/assets/environment/ulleung-highland-ridge-v1.webp' },
  ulleungGovernmentDistrictBackground: { key: 'ulleung-government-district-v3', path: '/assets/environment/ulleung-government-district-v3.webp' },
  yeongwolTrainingYardBackground: { key: 'yeongwol-training-yard-v1', path: '/assets/environment/yeongwol-training-yard-v1.webp' },
  yeongwolCommandHeadquartersBackground: { key: 'yeongwol-command-headquarters-v1', path: '/assets/environment/yeongwol-command-headquarters-v1.webp' },
  jeonjuWansanFieldBackground: { key: 'jeonju-wansan-field-v1', path: '/assets/environment/jeonju-wansan-field-v1.webp' },
  jeonjuPungnamGateBackground: { key: 'jeonju-pungnam-gate-v1', path: '/assets/environment/jeonju-pungnam-gate-v1.webp' },
  jeonjuCastleTownBackground: { key: 'jeonju-castle-town-v1', path: '/assets/environment/jeonju-castle-town-v1.webp' },
  osakaOuterHarborBackground: { key: 'osaka-outer-harbor-v1', path: '/assets/environment/campaign/osaka-outer-harbor-v1.webp' },
  settsuVillageBackground: { key: 'settsu-village-v1', path: '/assets/environment/campaign/settsu-village-v1.webp' },
  yamazakiHuntBackground: { key: 'yamazaki-hunt-v1', path: '/assets/environment/campaign/yamazaki-hunt-v1.webp' },
  osakaCastleTownBackground: { key: 'osaka-castle-town-v1', path: '/assets/environment/campaign/osaka-castle-town-v1.webp' },
  shogunKeepBackground: { key: 'shogun-keep-v1', path: '/assets/environment/campaign/shogun-keep-v1.webp' },
  busanjinSiegeBackground: { key: 'busanjin-siege-v2', path: '/assets/environment/campaign/busanjin-siege-v2.webp' },
  tangeumdaeBackground: { key: 'tangeumdae-v1', path: '/assets/environment/campaign/tangeumdae-v1.webp' },
  gyeongbokGwanghwamunBackground: { key: 'gyeongbok-gwanghwamun-v1', path: '/assets/environment/campaign/gyeongbok-gwanghwamun-v1.webp' },
  gyeongbokGeunjeongBackground: { key: 'gyeongbok-geunjeong-v1', path: '/assets/environment/campaign/gyeongbok-geunjeong-v1.webp' },
  gyeongbokInnerBackground: { key: 'gyeongbok-inner-v1', path: '/assets/environment/campaign/gyeongbok-inner-v1.webp' },
  hanseongSouthBackground: { key: 'hanseong-sungnyemun-v2', path: '/assets/environment/campaign/hanseong-sungnyemun-v2.webp' },
  hanseongMarketBackground: { key: 'hanseong-unjongga-v1', path: '/assets/environment/campaign/hanseong-unjongga-v1.webp' },
  changdeokgungAudienceBackground: { key: 'changdeokgung-audience-v2', path: '/assets/environment/campaign/changdeokgung-audience-v2.webp' },
  gaeseongSongdoBackground: { key: 'gaeseong-songdo-v1', path: '/assets/environment/campaign/gaeseong-songdo-v1.webp' },
  suwonDohobuBackground: { key: 'suwon-dohobu-v1', path: '/assets/environment/campaign/suwon-dohobu-v1.webp' },
  chungjuMokgyeBackground: { key: 'chungju-mokgye-v1', path: '/assets/environment/campaign/chungju-mokgye-v1.webp' },
  andongSeowonBackground: { key: 'andong-seowon-v1', path: '/assets/environment/campaign/andong-seowon-v1.webp' },
  pyongyangOuterBackground: { key: 'pyongyang-outer-v1', path: '/assets/environment/campaign/pyongyang-outer-v1.webp' },
  pyongyangDaedongGateBackground: { key: 'pyongyang-daedong-gate-v1', path: '/assets/environment/campaign/pyongyang-daedong-gate-v1.webp' },
  pyongyangInnerBackground: { key: 'pyongyang-inner-v1', path: '/assets/environment/campaign/pyongyang-inner-v1.webp' },
  namhansanFortressBackground: { key: 'namhansan-fortress-v1', path: '/assets/environment/campaign/namhansan-fortress-v1.webp' },
  ganghwaFortressBackground: { key: 'ganghwa-fortress-v1', path: '/assets/environment/campaign/ganghwa-fortress-v1.webp' },
  frontierCombatFx: { key: 'frontier-combat-fx-v1', path: '/assets/fx/frontier-combat-fx-v1.webp' },
  frontierCampProps: { key: 'frontier-camp-props-v1', path: '/assets/environment/props/frontier-camp-props-v1.webp' },
  gyeongbokForegrounds: {
    gwanghwamunOuterGate: {
      key: 'gyeongbok-gwanghwamun-outer-gate-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-gwanghwamun-outer-gate-v2.webp',
      x: 0, y: 428,
    },
    gwanghwamunInnerGate: {
      key: 'gyeongbok-gwanghwamun-inner-gate-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-gwanghwamun-inner-gate-v2.webp',
      x: 280, y: 36,
    },
    gwanghwamunSideCompounds: {
      key: 'gyeongbok-gwanghwamun-side-compounds-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-gwanghwamun-side-compounds-v2.webp',
      x: 0, y: 165,
    },
    geunjeongSouthGate: {
      key: 'gyeongbok-geunjeong-south-gate-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-geunjeong-south-gate-v2.webp',
      x: 0, y: 620,
    },
    geunjeongHall: {
      key: 'gyeongbok-geunjeong-hall-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-geunjeong-hall-v2.webp',
      x: 362, y: 0,
    },
    geunjeongSideCorridors: {
      key: 'gyeongbok-geunjeong-side-corridors-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-geunjeong-side-corridors-v2.webp',
      x: 0, y: 80,
    },
    innerSouthGate: {
      key: 'gyeongbok-inner-south-gate-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-inner-south-gate-v2.webp',
      x: 0, y: 648,
    },
    sajeongHall: {
      key: 'gyeongbok-inner-sajeong-hall-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-inner-sajeong-hall-v2.webp',
      x: 484, y: 202,
    },
    gangnyeongHall: {
      key: 'gyeongbok-inner-gangnyeong-hall-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-inner-gangnyeong-hall-v2.webp',
      x: 504, y: 0,
    },
    innerSideCompounds: {
      key: 'gyeongbok-inner-side-compounds-v2',
      path: '/assets/environment/campaign/foregrounds/gyeongbok-inner-side-compounds-v2.webp',
      x: 0, y: 0,
    },
  },
  pyongyangForegrounds: {
    outerNorthCamps: {
      key: 'pyongyang-outer-north-camps-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-outer-north-camps-v1.webp',
      x: 18, y: 140,
    },
    outerRampart: {
      key: 'pyongyang-outer-rampart-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-outer-rampart-v1.webp',
      x: 0, y: 326,
    },
    outerSouthSettlement: {
      key: 'pyongyang-outer-south-settlement-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-outer-south-settlement-v1.webp',
      x: 0, y: 548,
    },
    daedongNorthWorks: {
      key: 'pyongyang-daedong-north-works-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-daedong-north-works-v1.webp',
      x: 0, y: 0,
    },
    daedongRampart: {
      key: 'pyongyang-daedong-rampart-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-daedong-rampart-v1.webp',
      x: 0, y: 108,
    },
    daedongSiegeworks: {
      key: 'pyongyang-daedong-siegeworks-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-daedong-siegeworks-v1.webp',
      x: 0, y: 330,
    },
    innerNorthWall: {
      key: 'pyongyang-inner-north-wall-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-inner-north-wall-v1.webp',
      x: 0, y: 0,
    },
    innerUpperCompounds: {
      key: 'pyongyang-inner-upper-compounds-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-inner-upper-compounds-v1.webp',
      x: 20, y: 70,
    },
    innerLowerCompounds: {
      key: 'pyongyang-inner-lower-compounds-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-inner-lower-compounds-v1.webp',
      x: 0, y: 360,
    },
    innerSouthWall: {
      key: 'pyongyang-inner-south-wall-v1',
      path: '/assets/environment/campaign/foregrounds/pyongyang-inner-south-wall-v1.webp',
      x: 0, y: 690,
    },
  },
  jurchenVillageBackground: {
    key: 'jurchen-village-ground-v1',
    path: '/assets/environment/campaign/jurchen-village-ground-v1.webp',
  },
  manchuFrontierBackground: { key: 'manchu-frontier-v1', path: '/assets/environment/campaign/manchu-frontier-v1.webp' },
  awajiCoastBackground: { key: 'awaji-coast-v2', path: '/assets/environment/campaign/awaji-coast-v2.webp' },
  joseonGroundTile: { key: 'joseon-ground-tile-v2', path: '/assets/environment/tiles/joseon-ground-tile-v2.webp' },
  japanGroundTile: { key: 'japan-ground-tile-v2', path: '/assets/environment/tiles/japan-ground-tile-v2.webp' },
  northernGroundTile: { key: 'northern-ground-tile-v2', path: '/assets/environment/tiles/northern-ground-tile-v2.webp' },
  villageBackground: { key: 'joseon-village-v1', path: '/assets/environment/joseon-village-v1.png' },
  worldBackground: { key: 'moonshadow-village-world-v1', path: '/assets/environment/moonshadow-village-world-v1.webp' },
  mistwoodBackground: { key: 'cheongram-mistwood-v1', path: '/assets/environment/cheongram-mistwood-v1.png' },
  minepassBackground: { key: 'black-iron-minepass-v1', path: '/assets/environment/black-iron-minepass-v1.png' },
  moonfieldBackground: { key: 'moonlit-shadow-fields-v1', path: '/assets/environment/moonlit-shadow-fields-v1.png' },
  dungeonBackground: { key: 'muyeong-dungeon-base-v1', path: '/assets/environment/muyeong-dungeon-base-v1.webp' },
  transitions: {
    mistwoodVillage: { key: 'mistwood-village-feathered-v2', path: '/assets/environment/mistwood-village-feathered-v2.webp' },
    villageMinepass: { key: 'village-minepass-feathered-v2', path: '/assets/environment/village-minepass-feathered-v2.webp' },
    villageMoonfield: { key: 'village-moonfield-feathered-v2', path: '/assets/environment/village-moonfield-feathered-v2.webp' },
    ulleungCoastMeadow: { key: 'ulleung-coast-meadow-blend-v3', path: '/assets/environment/ulleung-coast-meadow-blend-v3.webp' },
    ulleungMeadowHunt: { key: 'ulleung-meadow-hunt-blend-v3', path: '/assets/environment/ulleung-meadow-hunt-blend-v3.webp' },
    ulleungHuntRidge: { key: 'ulleung-hunt-ridge-blend-v3', path: '/assets/environment/ulleung-hunt-ridge-blend-v3.webp' },
    ulleungRidgePrison: { key: 'ulleung-ridge-prison-blend-v3', path: '/assets/environment/ulleung-ridge-prison-blend-v3.webp' },
    ulleungPrisonGovernment: { key: 'ulleung-prison-government-blend-v3', path: '/assets/environment/ulleung-prison-government-blend-v3.webp' },
    settsuOsaka: {
      key: 'settsu-osaka-transition-v1',
      path: '/assets/environment/transitions/settsu-osaka-transition-v1.webp',
    },
    jurchenFrontier: {
      key: 'jurchen-frontier-transition-v1',
      path: '/assets/environment/transitions/jurchen-frontier-transition-v1.webp',
    },
    joseonGaeseongChangdeokgung: {
      key: 'joseon-gaeseong-changdeokgung-v2',
      path: '/assets/environment/transitions/joseon-gaeseong-changdeokgung-v2.webp',
    },
    joseonChangdeokgungUnjongga: {
      key: 'joseon-changdeokgung-unjongga-v2',
      path: '/assets/environment/transitions/joseon-changdeokgung-unjongga-v2.webp',
    },
    joseonUnjonggaSungnyemun: {
      key: 'joseon-unjongga-sungnyemun-v2',
      path: '/assets/environment/transitions/joseon-unjongga-sungnyemun-v2.webp',
    },
    joseonSungnyemunSuwon: {
      key: 'joseon-sungnyemun-suwon-v2',
      path: '/assets/environment/transitions/joseon-sungnyemun-suwon-v2.webp',
    },
    joseonSuwonChungju: {
      key: 'joseon-suwon-chungju-v2',
      path: '/assets/environment/transitions/joseon-suwon-chungju-v2.webp',
    },
    joseonChungjuAndong: {
      key: 'joseon-chungju-andong-v2',
      path: '/assets/environment/transitions/joseon-chungju-andong-v2.webp',
    },
  },
  props: {
    betaRoadsideProps: {
      key: 'beta-roadside-props-v1',
      path: '/assets/environment/beta/beta-roadside-props-v1.webp',
    },
    episode2VillageProps: {
      key: 'episode2-joseon-village-prop-atlas-v2',
      path: '/assets/environment/props/episode2-joseon-village-prop-atlas-v2.png',
    },
    episode2WaterwheelWheel: {
      key: 'episode2-waterwheel-wheel-v1',
      path: '/assets/environment/props/episode2-waterwheel-wheel-v1.png',
    },
    ambient: {
      reedCluster: {
        key: 'reed-cluster-ambient-v1',
        path: '/assets/environment/props/ambient/reed-cluster-ambient-v1.png',
      },
      waterRipple: {
        key: 'water-ripple-ambient-v1',
        path: '/assets/environment/props/ambient/water-ripple-ambient-v1.png',
      },
      coastalBoat: {
        key: 'coastal-boat-ambient-v1',
        path: '/assets/environment/props/ambient/coastal-boat-ambient-v1.png',
      },
      coastalBoatHull: {
        key: 'coastal-boat-hull-ambient-v1',
        path: '/assets/environment/props/ambient/coastal-boat-hull-ambient-v1.png',
      },
      windmill: {
        key: 'wooden-windmill-ambient-v1',
        path: '/assets/environment/props/ambient/wooden-windmill-ambient-v1.png',
      },
      banner: {
        key: 'joseon-banner-ambient-v1',
        path: '/assets/environment/props/ambient/joseon-banner-ambient-v1.png',
      },
      flagPole: {
        key: 'joseon-flag-pole-ambient-v1',
        path: '/assets/environment/props/ambient/joseon-flag-pole-ambient-v1.png',
      },
      flagCloth: {
        key: 'joseon-flag-cloth-ambient-v1',
        path: '/assets/environment/props/ambient/joseon-flag-cloth-ambient-v1.png',
      },
      hangingLantern: {
        key: 'hanging-lantern-ambient-v1',
        path: '/assets/environment/props/ambient/hanging-lantern-ambient-v1.png',
      },
    },
    spiritShrine: { key: 'spirit-shrine-v1', path: '/assets/environment/props/spirit-shrine-v1.png' },
    brokenCart: { key: 'broken-cart-v1', path: '/assets/environment/props/broken-cart-v1.png' },
    blacksmithHammer: { key: 'blacksmith-hammer-v1', path: '/assets/environment/props/blacksmith-hammer-v1.png' },
    blacksmithWorkstation: { key: 'blacksmith-workstation-v1', path: '/assets/environment/props/blacksmith-workstation-v1.png' },
    ulleungTrainingPine: { key: 'ulleung-training-pine-v2', path: '/assets/environment/props/ulleung-training-pine-v2.png' },
    joseonTreeSpecies: {
      key: 'joseon-tree-species-atlas-v1',
      path: '/assets/environment/props/joseon-tree-species-atlas-v1.png',
    },
    ulleungAdventureProps: { key: 'ulleung-adventure-prop-atlas-v1', path: '/assets/environment/props/ulleung-adventure-prop-atlas-v1.png' },
    villageFarmPlotStages: {
      key: 'joseon-farm-plot-stages-v4',
      path: '/assets/environment/props/joseon-farm-plot-stages-v4.png',
    },
    jurchenVillageStructures: {
      key: 'jurchen-village-structures-v1',
      path: '/assets/environment/props/jurchen-village-structures-v1.png',
    },
    worldTransitionProps: {
      key: 'world-transition-prop-atlas-v1',
      path: '/assets/environment/props/world-transition-prop-atlas-v1.webp',
    },
    japanRegionProps: {
      key: 'japan-region-prop-atlas-v1',
      path: '/assets/environment/props/japan-region-prop-atlas-v1.webp',
    },
    worldTerrainFeathers: {
      key: 'world-terrain-feather-atlas-v1',
      path: '/assets/environment/props/world-terrain-feather-atlas-v1.webp',
    },
    worldGroundDetails: {
      key: 'world-ground-detail-atlas-v2',
      path: '/assets/environment/props/world-ground-detail-atlas-v2.png',
    },
    worldNaturalRoads: {
      key: 'world-natural-road-atlas-v2',
      path: '/assets/environment/props/world-natural-road-atlas-v2.png',
    },
    worldSeamRoads: {
      key: 'world-seam-road-atlas-v4',
      path: '/assets/environment/props/world-seam-road-atlas-v4.png',
    },
    yeongwolOuterGate: { key: 'yeongwol-outer-gate-v1', path: '/assets/environment/props/yeongwol-outer-gate-v1.png' },
    yeongwolInnerGate: { key: 'yeongwol-inner-gate-v1', path: '/assets/environment/props/yeongwol-inner-gate-v1.png' },
    yeongwolWatchtower: { key: 'yeongwol-watchtower-v1', path: '/assets/environment/props/yeongwol-watchtower-v1.png' },
    yeongwolBarracks: { key: 'yeongwol-barracks-v1', path: '/assets/environment/props/yeongwol-barracks-v1.png' },
    yeongwolPalisade: { key: 'yeongwol-palisade-v1', path: '/assets/environment/props/yeongwol-palisade-v1.png' },
    yeongwolArmoryProps: { key: 'yeongwol-armory-props-v1', path: '/assets/environment/props/yeongwol-armory-props-v1.png' },
    yeongwolHeadquartersHall: { key: 'yeongwol-hq-main-hall-foreground-v1', path: '/assets/environment/props/yeongwol-hq-main-hall-foreground-v1.png' },
  },
  portalSigns: { key: 'world-sign-atlas-v1', path: '/assets/ui/world-sign-atlas-v1.png' },
  worldMapLandmarks: {
    key: 'world-map-landmark-atlas-v1',
    path: '/assets/ui/world-map-landmark-atlas-v1.png',
  },
  combatCursor: { key: 'sword-target-cursor-v1', path: '/assets/ui/sword-target-cursor-v1.png' },
  projectiles: {
    joseonArrow: { key: 'joseon-arrow-projectile-v1', path: '/assets/fx/joseon-arrow-projectile-v1.png' },
  },
  combatImpacts: {
    key: 'beta-combat-impact-atlas-v1',
    path: '/assets/fx/beta-combat-impact-atlas-v1.png',
  },
  statusEffects: {
    key: 'beta-status-effects-v1',
    path: '/assets/ui/beta-status-effects-v1.png',
  },
  dungeonProps: { key: 'dungeon-prop-atlas-v1', path: '/assets/environment/props/dungeon-prop-atlas-v1.png' },
  dungeonWalls: { key: 'dungeon-wall-atlas-v1', path: '/assets/environment/props/dungeon-wall-atlas-v1.png' },
  dungeonTelegraphs: { key: 'dungeon-telegraph-atlas-v1', path: '/assets/fx/dungeon-telegraph-atlas-v1.png' },
  playerUnequipped: { key: 'joseon-hero-base-body-v8', path: '/assets/characters/joseon-hero-base-body-v8.png' },
  playerWeaponReadyBody: { key: 'joseon-hero-weapon-ready-body-v3', path: '/assets/characters/joseon-hero-weapon-ready-body-v3.png' },
  playerWeaponAttackBody: { key: 'joseon-hero-weapon-attack-body-v1', path: '/assets/characters/joseon-hero-weapon-attack-body-v1.webp' },
  frontierArcher: { key: 'hajin-frontier-archer-actions-v2', path: '/assets/characters/hajin-frontier-archer-actions-v2.png' },
  frontierMelee: { key: 'harlan-melee-ready-actions-v1', path: '/assets/characters/harlan-melee-ready-actions-v1.png' },
  osakaMudang: { key: 'osaka-mudang-actions-v1', path: '/assets/characters/osaka-mudang-actions-v1.png' },
  gwanghaePrince: { key: 'joseon-gwanghae-actions-v2', path: '/assets/characters/joseon-gwanghae-actions-v2.png' },
  playerArmorOnly: { key: 'joseon-hero-armor-only-v3', path: '/assets/characters/joseon-hero-armor-only-v3.png' },
  playerFullyEquipped: { key: 'joseon-hero-fully-equipped-v3', path: '/assets/characters/joseon-hero-fully-equipped-v3.png' },
  playerArmorLayer: { key: 'joseon-hero-armor-layer-v4', path: '/assets/characters/joseon-hero-armor-layer-v4.png' },
  playerArmorLayers: {
    'hunter-durumagi': { key: 'joseon-hero-armor-layer-v4', path: '/assets/characters/joseon-hero-armor-layer-v4.png' },
    'warden-durumagi': { key: 'joseon-hero-warden-layer-v2', path: '/assets/characters/joseon-hero-warden-layer-v2.png' },
    'tiger-pelt-armor': { key: 'joseon-hero-tiger-pelt-layer-v2', path: '/assets/characters/joseon-hero-tiger-pelt-layer-v2.png' },
  },
  playerWeaponAttackArmorLayers: {
    'hunter-durumagi': { key: 'joseon-hero-hunter-weapon-attack-layer-v1', path: '/assets/characters/joseon-hero-hunter-weapon-attack-layer-v1.webp' },
    'warden-durumagi': { key: 'joseon-hero-warden-weapon-attack-layer-v1', path: '/assets/characters/joseon-hero-warden-weapon-attack-layer-v1.webp' },
  },
  playerWeaponReadyArmorLayers: {
    'hunter-durumagi': { key: 'joseon-hero-hunter-weapon-ready-layer-v2', path: '/assets/characters/joseon-hero-hunter-weapon-ready-layer-v2.webp' },
    'warden-durumagi': { key: 'joseon-hero-warden-weapon-ready-layer-v2', path: '/assets/characters/joseon-hero-warden-weapon-ready-layer-v2.webp' },
    'tiger-pelt-armor': { key: 'joseon-hero-tiger-pelt-weapon-ready-layer-v2', path: '/assets/characters/joseon-hero-tiger-pelt-weapon-ready-layer-v2.webp' },
  },
  playerWeapons: {
    'worn-hwando': {
      key: 'weapon-worn-hwando-world-v1', path: '/assets/weapons/worn-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'dokkaebi-club': {
      key: 'weapon-dokkaebi-club-world-v1', path: '/assets/weapons/dokkaebi-club-world-v1.png', grip: { x: 128, y: 50 },
    },
    'moonsteel-hwando': {
      key: 'weapon-moonsteel-hwando-world-v1', path: '/assets/weapons/moonsteel-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'ember-hwando': {
      key: 'weapon-ember-hwando-world-v1', path: '/assets/weapons/ember-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'frost-hwando': {
      key: 'weapon-frost-hwando-world-v1', path: '/assets/weapons/frost-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'storm-hwando': {
      key: 'weapon-storm-hwando-world-v1', path: '/assets/weapons/storm-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'venom-hwando': {
      key: 'weapon-venom-hwando-world-v1', path: '/assets/weapons/venom-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'gale-hwando': {
      key: 'weapon-gale-hwando-world-v1', path: '/assets/weapons/gale-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'earth-hwando': {
      key: 'weapon-earth-hwando-world-v1', path: '/assets/weapons/earth-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'shadow-hwando': {
      key: 'weapon-shadow-hwando-world-v1', path: '/assets/weapons/shadow-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'bear-claw-gauntlet': {
      key: 'weapon-bear-claw-gauntlet-world-v1', path: '/assets/weapons/bear-claw-gauntlet-world-v1.png', grip: { x: 128, y: 50 },
    },
    'chiaksan-claw-knife': {
      key: 'weapon-chiaksan-claw-knife-world-v1', path: '/assets/weapons/chiaksan-claw-knife-world-v1.png', grip: { x: 128, y: 50 },
    },
    'saltfield-ritual-knife': {
      key: 'weapon-saltfield-ritual-knife-world-v1', path: '/assets/weapons/saltfield-ritual-knife-world-v1.png', grip: { x: 128, y: 50 },
    },
    'geoje-anchor-hwando': {
      key: 'weapon-geoje-anchor-hwando-world-v1', path: '/assets/weapons/geoje-anchor-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'hwangju-moonsteel-spear': {
      key: 'weapon-hwangju-moonsteel-spear-world-v1', path: '/assets/weapons/hwangju-moonsteel-spear-world-v1.png', grip: { x: 128, y: 50 },
    },
    'pyeongchang-leopard-knife': {
      key: 'weapon-pyeongchang-leopard-knife-world-v1', path: '/assets/weapons/pyeongchang-leopard-knife-world-v1.png', grip: { x: 128, y: 50 },
    },
    'cheongju-kiln-hwando': {
      key: 'weapon-cheongju-kiln-hwando-world-v1', path: '/assets/weapons/cheongju-kiln-hwando-world-v1.png', grip: { x: 128, y: 50 },
    },
    'gunsan-drowned-blade': {
      key: 'weapon-gunsan-drowned-blade-world-v1', path: '/assets/weapons/gunsan-drowned-blade-world-v1.png', grip: { x: 128, y: 50 },
    },
  },
  villageCommoner: { key: 'joseon-village-commoner-v1', path: '/assets/characters/joseon-village-commoner-v1.png' },
  villageFieldPloughman: {
    key: 'joseon-field-ploughman-actions-v1',
    path: '/assets/characters/joseon-field-ploughman-actions-v1.png',
  },
  villageFemaleFarmer: {
    key: 'joseon-female-farmer-actions-v1',
    path: '/assets/characters/joseon-female-farmer-actions-v1.png',
  },
  villageFemaleWaterer: {
    key: 'joseon-female-waterer-actions-v1',
    path: '/assets/characters/joseon-female-waterer-actions-v1.png',
  },
  japaneseCivilianWoman: {
    key: 'japanese-civilian-woman-actions-v1',
    path: '/assets/characters/japanese-civilian-woman-actions-v1.png',
  },
  ulleungOppressedVillager: { key: 'ulleung-oppressed-villager-actions-v1', path: '/assets/characters/ulleung-oppressed-villager-actions-v1.png' },
  monsters: {
    'osaka-overseer': { key: 'japanese-swordsman-actions-v1', path: '/assets/monsters/japanese-swordsman-actions-v1.png' },
    'osaka-ronin': { key: 'japanese-swordsman-actions-v1', path: '/assets/monsters/japanese-swordsman-actions-v1.png' },
    'osaka-gunner': { key: 'japanese-gunner-actions-v1', path: '/assets/monsters/japanese-gunner-actions-v1.png' },
    'ulleung-hare': { key: 'ulleung-hare-actions-v1', path: '/assets/monsters/ulleung-hare-actions-v1.png' },
    'ulleung-water-deer': { key: 'ulleung-water-deer-actions-v1', path: '/assets/monsters/ulleung-water-deer-actions-v1.png' },
    'ulleung-sangun': { key: 'ulleung-sangun-actions-v1', path: '/assets/monsters/ulleung-sangun-actions-v1.png' },
    'ulleung-guard': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'ulleung-veteran': { key: 'joseon-spearman-actions-v1', path: '/assets/monsters/joseon-spearman-actions-v1.png' },
    'ulleung-archer': { key: 'joseon-archer-actions-v1', path: '/assets/monsters/joseon-archer-actions-v1.png' },
    'ulleung-executioner': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'ulleung-captain': { key: 'joseon-pododaejang-actions-v1', path: '/assets/monsters/joseon-pododaejang-actions-v1.png' },
    'ulleung-magistrate': { key: 'ulleung-magistrate-actions-v1', path: '/assets/bosses/ulleung-magistrate-actions-v1.png' },
    'wako-raider': { key: 'japanese-swordsman-actions-v1', path: '/assets/monsters/japanese-swordsman-actions-v1.png' },
    'wako-archer': { key: 'japanese-archer-actions-v1', path: '/assets/monsters/japanese-archer-actions-v1.png' },
    'wako-captain': { key: 'japanese-general-actions-v1', path: '/assets/monsters/japanese-general-actions-v1.png' },
    'yeongwol-swordsman': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'yeongwol-spearman': { key: 'joseon-spearman-actions-v1', path: '/assets/monsters/joseon-spearman-actions-v1.png' },
    'yeongwol-archer': { key: 'joseon-archer-actions-v1', path: '/assets/monsters/joseon-archer-actions-v1.png' },
    'yeongwol-shield': { key: 'joseon-shield-guard-actions-v1', path: '/assets/monsters/joseon-shield-guard-actions-v1.png' },
    'yeongwol-commander': { key: 'joseon-pododaejang-actions-v1', path: '/assets/monsters/joseon-pododaejang-actions-v1.png' },
    'jeonju-swordsman': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'jeonju-spearman': { key: 'joseon-spearman-actions-v1', path: '/assets/monsters/joseon-spearman-actions-v1.png' },
    'jeonju-archer': { key: 'joseon-archer-actions-v1', path: '/assets/monsters/joseon-archer-actions-v1.png' },
    'jeonju-shield': { key: 'joseon-shield-guard-actions-v1', path: '/assets/monsters/joseon-shield-guard-actions-v1.png' },
    'jeonju-commander': { key: 'joseon-pododaejang-actions-v1', path: '/assets/monsters/joseon-pododaejang-actions-v1.png' },
    'jeonju-militia-sickle': { key: 'joseon-peasant-militia-actions-v1', path: '/assets/characters/joseon-peasant-militia-actions-v1.png' },
    'japanese-sika-deer': { key: 'ulleung-water-deer-actions-v1', path: '/assets/monsters/ulleung-water-deer-actions-v1.png' },
    'japanese-wild-boar': { key: 'boar-actions', path: '/assets/monsters/boar-actions.webp' },
    'japanese-swordsman': { key: 'japanese-swordsman-actions-v1', path: '/assets/monsters/japanese-swordsman-actions-v1.png' },
    'japanese-spearman': { key: 'japanese-spearman-actions-v1', path: '/assets/monsters/japanese-spearman-actions-v1.png' },
    'japanese-archer': { key: 'japanese-archer-actions-v1', path: '/assets/monsters/japanese-archer-actions-v1.png' },
    'japanese-gunner': { key: 'japanese-gunner-actions-v1', path: '/assets/monsters/japanese-gunner-actions-v1.png' },
    'japanese-general': { key: 'japanese-general-actions-v1', path: '/assets/monsters/japanese-general-actions-v1.png' },
    'japanese-shogun': { key: 'japanese-shogun-actions-v1', path: '/assets/monsters/japanese-shogun-actions-v1.png' },
    'manchu-lancer': { key: 'jurchen-lancer-actions-v1', path: '/assets/monsters/jurchen-lancer-actions-v1.png' },
    'manchu-archer': { key: 'jurchen-archer-actions-v1', path: '/assets/monsters/jurchen-archer-actions-v1.png' },
    'manchu-cavalry': { key: 'jurchen-cavalry-actions-v1', path: '/assets/monsters/jurchen-cavalry-actions-v1.png' },
    'manchu-captain': { key: 'jurchen-commander-actions-v1', path: '/assets/monsters/jurchen-commander-actions-v1.png' },
    'manchu-chieftain': { key: 'jurchen-chieftain-actions-v1', path: '/assets/monsters/jurchen-chieftain-actions-v1.png' },
    'joseon-border-swordsman': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'joseon-border-spearman': { key: 'joseon-spearman-actions-v1', path: '/assets/monsters/joseon-spearman-actions-v1.png' },
    'joseon-border-archer': { key: 'joseon-archer-actions-v1', path: '/assets/monsters/joseon-archer-actions-v1.png' },
    'joseon-border-commander': { key: 'joseon-pododaejang-actions-v1', path: '/assets/monsters/joseon-pododaejang-actions-v1.png' },
    'royal-guard': { key: 'ulleung-guard-actions-v1', path: '/assets/monsters/ulleung-guard-actions-v1.png' },
    'joseon-prince': { key: 'joseon-crown-prince-actions-v1', path: '/assets/characters/joseon-crown-prince-actions-v1.png' },
    'joseon-civilian': { key: 'joseon-civilian-actions-v1', path: '/assets/characters/ulleung-oppressed-villager-actions-v1.png' },
    'korean-gray-wolf': { key: 'korean-gray-wolf-actions-v1', path: '/assets/monsters/korean-wolf-actions-v1.png' },
    dokkaebi: { key: 'dokkaebi-actions', path: '/assets/monsters/dokkaebi-actions.png' },
    boar: { key: 'boar-actions', path: '/assets/monsters/boar-actions.webp' },
    bandit: { key: 'bandit-actions', path: '/assets/monsters/bandit-actions.png' },
    'bamboo-spirit': { key: 'bamboo-spirit-actions', path: '/assets/monsters/bamboo-spirit-actions.png' },
    'mine-golem': { key: 'mine-golem-actions', path: '/assets/monsters/mine-golem-actions.png' },
    'moon-revenant': { key: 'moon-revenant-actions', path: '/assets/monsters/moon-revenant-actions.png' },
    'wonju-bear': { key: 'wonju-bear-actions-v1', path: '/assets/monsters/wonju-bear-actions-v1.png' },
    'gangneung-haetae': { key: 'gangneung-haetae-actions-v1', path: '/assets/monsters/gangneung-haetae-actions-v1.png' },
    'haeju-crane': { key: 'haeju-crane-actions-v1', path: '/assets/monsters/haeju-crane-actions-v1.png' },
    'geoje-sea-wraith': { key: 'geoje-sea-wraith-actions-v1', path: '/assets/monsters/geoje-sea-wraith-actions-v1.png' },
    'episode2-red-fox': { key: 'episode2-red-fox-actions-v1', path: '/assets/monsters/episode2-red-fox-actions-v1.png' },
    'episode2-mountain-leopard': { key: 'episode2-mountain-leopard-actions-v1', path: '/assets/monsters/episode2-mountain-leopard-actions-v1.png' },
    'episode2-marsh-wisp': { key: 'episode2-marsh-wisp-actions-v1', path: '/assets/monsters/episode2-marsh-wisp-actions-v1.png' },
    'episode2-stone-dokkaebi': { key: 'episode2-stone-dokkaebi-actions-v1', path: '/assets/monsters/episode2-stone-dokkaebi-actions-v1.png' },
  },
  bosses: {
    'chain-miner': { key: 'boss-chain-miner-actions', path: '/assets/bosses/chain-miner-actions-v1.png' },
    'bone-jangseung': { key: 'boss-bone-jangseung-actions', path: '/assets/bosses/bone-jangseung-actions-v1.png' },
    'flame-shaman': { key: 'boss-flame-shaman-actions', path: '/assets/bosses/flame-shaman-actions-v1.png' },
    'iron-tiger': { key: 'boss-iron-tiger-actions', path: '/assets/bosses/iron-tiger-actions-v1.png' },
    'headless-general': { key: 'boss-headless-general-actions', path: '/assets/bosses/headless-general-actions-v1.png' },
    'drowned-warden': { key: 'boss-drowned-warden-actions', path: '/assets/bosses/drowned-warden-actions-v1.png' },
    'eclipse-dokkaebi': { key: 'boss-eclipse-dokkaebi-actions', path: '/assets/bosses/eclipse-dokkaebi-actions-v1.png' },
    'black-iron-giant': { key: 'boss-black-iron-giant-actions', path: '/assets/bosses/black-iron-giant-actions-v1.png' },
    'sealed-monk': { key: 'boss-sealed-monk-actions', path: '/assets/bosses/sealed-monk-actions-v1.png' },
    'shadow-magistrate': { key: 'boss-shadow-magistrate-actions', path: '/assets/bosses/shadow-magistrate-actions-v1.png' },
  },
} as const;

export const PLAYER_ACTION_FRAME = { width: 256, height: 256, framesPerRow: 8 } as const;
export const MONSTER_FRAME = { width: 256, height: 256, framesPerRow: 8 } as const;
